language: java
jdk: openjdk11
env:
  global:
  - secure: JIC6wNnRu5UlKHuzJbiQ8RFF4vlIesZ2X2mbgu4AEIbZrKva8r6hlTIHN38tS0C2s5Sq5Dsv7+MIDtfOw7NyrSb6uyy9yO+SfdFTE49n5OeJuBy8fLIFeQyp6sH95D7q21xPIrr2PoX+U4X3ng6oTmB1xzNEgj/bcJm3iy/ZLQrYe2iH7vn8vmLPb1mz4dpg/j9RoJ3EVT5AP8UOdAC4JRCfFVSp/iP/IiajGfSun3cdLL9fTZIuRx3h5xuxity0OcFIUT5XR55NdeF6GF7h0JbggDWQjRzHXR/Ex6H0vLRphLGaqNGkzF8qR1PdfxcoHAbrpXCcGdZ2A2FqGPSPlKl9RpkK86O6YFrLrCzpfxkzmpVVTVytIb16NDw538t/I1qOD6BneaVa3JY4/C5f05xaKAWA1jLxEEE4cgFled0sAK8q9vQ8wycVF6ygfRTwoK/jQtbIzawxXjLebbUfMWBC8jx908gP6Mk9ypopI2cYtgw0+9y4QwbPH8LNkM/PoQPtwBWh4pI2CljWFVMrG26xP4JLL13tzu49KNO+rSoBCi7DfRrNdoDDoLNVEXaOOetyHiGlprv/iU1KkSwt7qi7W0DSB9bp1V1elpV3csemqIsv/NSh1IjdYrSBaiENFeuzREOibrmjPP2IzZS3Gfp2T5CNEffExDWNyOYyCQw=
  - secure: Uu3PnX5hbaacrJodz26c/x+bWifKkDzq9FV0nKLswB+VsavkHLjJG1fwRURK3ZF+LRSzZyJ0liULyf1HpZci+CY/RKtIO1tHR+Yg64hXqDdrbJRoXRlQQ9XnYUPZuQGI0jtJxdG3OXXvXFYhtA1ThMfSW4hVHslZbD3JH3Vq8V85IVDZCyPRajUjJIrQjxo9Nu1R1ItM299vUt2MEVY+ta0sesYfpcp2wQRY6OX4CSuOki8TeGUJ0M1vgI819PZ+i2y/+w7St8eFDvtfoBGHDxXkhiB6X3qAhVctd6NIfCajBfs3M5hyJNT+aBAv7JOewhjJWs0GpexS3Lmc1/gR2ZLgp2yZ5vUVETI/ZvS34UrqeYDQC6PEYLCEhkFJbJsgJE2Xnee3ldX5yK9xLtkYcMLpP9mLY1yNfC2531WCN3dYqoSkihLZV2jV5K8yJTYL762vwNbNikbPOR/EVwOS0CyizT2JRvuoJVChg5VYn8PmcYiBGBGYs51h9xREEM7Oc6rFp4HEhuBSUvoJGmUdbEm5f3/NWaDfV58c+35dRcqPTiU2VUw27syVfP1S5kVsz8+x3jLRkPMv/fpIaztJIgtx9eQd9FSxbJvKwGPymyrJIwhuEUPWae4yxAu0HNUmJYGVdjb44yEnoxemCtoBM19/yXT7Rj3WKPBz9LVu8Ew=
install: skip
script: mvn --settings .mvn/settings.xml install && ([[ $TRAVIS_BRANCH != "master" ]] || mvn --settings .mvn/settings.xml -DskipTests=true deploy)
sudo: false
cache:
  directories: "$HOME/.m2"
branches:
  except: gh-pages
notifications:
  email: joerg.hohwiller@googlemail.com
