image:https://m-m-m.github.io/logo.svg[logo,width="150",link="https://m-m-m.github.io"]

image:https://img.shields.io/github/license/m-m-m/nls.svg?label=License["Apache License, Version 2.0",link=https://github.com/m-m-m/nls/blob/master/LICENSE]
image:https://github.com/m-m-m/nls/actions/workflows/build.yml/badge.svg["Build Status",link="https://github.com/m-m-m/nls/actions/workflows/build.yml"]

= mmm-nls

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-nls.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-nls/javadoc.svg["JavaDoc",link=https://javadoc.io/doc/io.github.m-m-m/mmm-nls]

The module `io.github.mmm.nls` (artifactId `mmm-nls`) provides advanced native-language-support.
For a motivation and introduction please read the JavaDocs (see badge above).

== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-nls</artifactId>
  <!--<version>${mmmVersion}</version>-->
</dependency>
```
Gradle Dependency:
```
implementation 'io.github.m-m-m:mmm-nls:${mmmVersion}'
```
For `${mmmVersion}` please fill in the latest version that you can find in the badge above.

Module Dependency:
```java
  requires transitive io.github.mmm.nls;
```

= mmm-nls-cli

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-nls-cli.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-nls-cli/javadoc.svg["JavaDoc",link=https://javadoc.io/doc/io.github.m-m-m/mmm-nls-cli]

The module `io.github.mmm.nls.cli` (artifactId `mmm-nls-cli`) provides NLS for command-line-interfaces (CLI).
For a motivation and introduction please read the JavaDocs (see badge above).

== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-nls-cli</artifactId>
  <version>${mmm.nls.version}</version>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.nls.cli;
```

= mmm-nls-sync

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-nls-sync.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-nls-sync/javadoc.svg["JavaDoc",link=https://javadoc.io/doc/io.github.m-m-m/mmm-nls-sync]

The module `io.github.mmm.nls.sync` (artifactId `mmm-nls-sync`) provides the tool `io.github.mmm.nls.sync.NlsSynchronizer` allowing to synchronize your `NlsBundle` classes with all your available resource-bundle properties files.
For a motivation and introduction please read the JavaDocs (see badge above).

== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-nls-sync</artifactId>
  <version>${mmm.nls.version}</version>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.nls.sync;
```
